### ISSUE TITLE
Java extension unhappy in code-server

### ISSUE THREAD

**Issue by russau** [monostream/code-server#1]
https://github.com/monostream/code-server/blob/f002441eb15bde00cc09793364b2e3e0d8e133ed/Dockerfile#L139

FYI  - I've have to downgrade to version 0.43 @ https://download.jboss.org/jbosstools/jdt.ls/staging/java-0.43.0-1473.vsix.  code-server doesn't appear happy with the newest version, it just appears as a disabled extension.

**Comment by shakeebatme** [comment]
This helped.
